package cleaners

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const maxModuleDepth = 8

type artifactRule struct {
	dir       string
	sibling   string
	reinstall string
}

var artifactRules = []artifactRule{
	{dir: "node_modules", sibling: "package.json", reinstall: "npm/bun/pnpm install"},
	{dir: "target", sibling: "Cargo.toml", reinstall: "cargo build"},
	{dir: ".venv", sibling: "", reinstall: "recreate the virtualenv"},
	{dir: "Pods", sibling: "Podfile", reinstall: "pod install"},
	{dir: ".next", sibling: "package.json", reinstall: "next build / next dev"},
	{dir: ".turbo", sibling: "package.json", reinstall: "regenerated by turbo"},
}

func ModuleRoots() []string {
	var roots []string
	for _, r := range []string{"~/Documents", "~/dev", "~/code", "~/projects"} {
		p := expand(r)
		if info, err := os.Stat(p); err == nil && info.IsDir() {
			roots = append(roots, p)
		}
	}
	return roots
}

func ModuleTargets(roots []string) []*Target {
	var targets []*Target
	for _, root := range roots {
		walkModules(root, root, 0, &targets)
	}
	return targets
}

func walkModules(root, dir string, depth int, targets *[]*Target) {
	if depth > maxModuleDepth {
		return
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	for _, e := range entries {
		if !e.IsDir() || strings.HasPrefix(e.Name(), ".") && !isArtifactName(e.Name()) {
			continue
		}
		path := filepath.Join(dir, e.Name())
		if rule, ok := matchArtifact(dir, e.Name()); ok {
			if t := moduleTarget(root, path, rule); t != nil {
				*targets = append(*targets, t)
			}
			continue
		}
		if !strings.HasPrefix(e.Name(), ".") {
			walkModules(root, path, depth+1, targets)
		}
	}
}

func isArtifactName(name string) bool {
	for _, r := range artifactRules {
		if r.dir == name {
			return true
		}
	}
	return false
}

func matchArtifact(parent, name string) (artifactRule, bool) {
	for _, r := range artifactRules {
		if r.dir != name {
			continue
		}
		if r.sibling == "" {
			return r, true
		}
		if _, err := os.Stat(filepath.Join(parent, r.sibling)); err == nil {
			return r, true
		}
	}
	return artifactRule{}, false
}

func moduleTarget(root, path string, rule artifactRule) *Target {
	project := filepath.Dir(path)
	rel, err := filepath.Rel(filepath.Dir(root), project)
	if err != nil {
		rel = filepath.Base(project)
	}
	used := projectLastUsed(project, rule.dir)
	return &Target{
		ID:       "module:" + path,
		Name:     filepath.Join(rel, rule.dir),
		Tier:     Careful,
		Note:     "restore with " + rule.reinstall,
		LastUsed: used,
		paths:    []string{path},
		Explain: Explain{
			What:  fmt.Sprintf("Build artifacts of %s.", shortPath(project)),
			After: fmt.Sprintf("The project itself is untouched. Restore with %s.", rule.reinstall),
		},
	}
}

func projectLastUsed(project, artifactDir string) time.Time {
	if ts := spotlightLastUsed(project); !ts.IsZero() {
		return ts
	}
	var newest time.Time
	entries, err := os.ReadDir(project)
	if err != nil {
		return newest
	}
	for _, e := range entries {
		if e.Name() == artifactDir || isArtifactName(e.Name()) {
			continue
		}
		if info, err := e.Info(); err == nil && info.ModTime().After(newest) {
			newest = info.ModTime()
		}
	}
	return newest
}
